package com.openvehicles.OVMS;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;

public class CarData implements Serializable {
	private static final long serialVersionUID = 9069218298370983462L;
	public double Data_Altitude = 0.0D;
	public boolean Data_AmbientTemperatureDataStale = false;
	public boolean Data_BonnetOpen = false;
	public boolean Data_CANWriteEnabled = false;
	public boolean Data_CarLocked = false;
	public String Data_CarModuleFirmwareVersion = "";
	public String Data_CarModuleGSMSignalLevel = "";
	public boolean Data_CarPoweredON = false;
	public String Data_CarType = "";
	public int Data_CarsConnected = 0;
	public int Data_ChargeAmpsLimit = 0;
	public int Data_ChargeCurrent = 0;
	public String Data_ChargeMode = "";
	public int Data_ChargeMode_raw = 0;
	public boolean Data_ChargePortOpen = false;
	public String Data_ChargeState = "";
	public int Data_ChargeState_raw = 0;
	public int Data_ChargeSubstate = 0;
	public int Data_ChargerB4State = 0;
	public double Data_ChargerKWHConsumed = 0.0D;
	public boolean Data_Charging = false;
	public boolean Data_CoolingPumpON_DoorState3 = false;
	public double Data_Direction = 0.0D;
	public String Data_DistanceUnit = "";
	public int Data_EstimatedRange = 0;
	public double Data_FLWheelPressure = 0.0D;
	public double Data_FLWheelTemperature = 0.0D;
	public double Data_FRWheelPressure = 0.0D;
	public double Data_FRWheelTemperature = 0.0D;
	public LinkedHashMap<Integer, String> Data_Features = new LinkedHashMap();
	public Date Data_Features_LastRefreshed = null;
	public GPRSUtilization Data_GPRSUtilization = null;
	public boolean Data_GPSDataStale = false;
	public boolean Data_GPSLocked = false;
	public boolean Data_HandBrakeApplied = false;
	public boolean Data_HeadlightsON = false;
	public int Data_IdealRange = 0;
	public Date Data_LastCarUpdate;
	public long Data_LastCarUpdate_raw = 0L;
	public double Data_Latitude = 0.0D;
	public boolean Data_LeftDoorOpen = false;
	public int Data_LineVoltage = 0;
	public double Data_Longitude = 0.0D;
	public String Data_OVMSServerFirmwareVersion = "";
	public double Data_Odometer = 0.0D;
	public boolean Data_PEM_Motor_Battery_TemperaturesDataStale = false;
	public boolean Data_PINLocked = false;
	public LinkedHashMap<Integer, String> Data_Parameters = new LinkedHashMap();
	public Date Data_Parameters_LastRefreshed = null;
	public Date Data_ParkedTime;
	public double Data_ParkedTime_raw = 0.0D;
	public boolean Data_PilotPresent = false;
	public double Data_RLWheelPressure = 0.0D;
	public double Data_RLWheelTemperature = 0.0D;
	public double Data_RRWheelPressure = 0.0D;
	public double Data_RRWheelTemperature = 0.0D;
	public boolean Data_RightDoorOpen = false;
	public int Data_SOC = 0;
	public double Data_Speed = 0.0D;
	public boolean Data_TPMSDataStale = false;
	public double Data_TemperatureAmbient = 0.0D;
	public double Data_TemperatureBattery = 0.0D;
	public double Data_TemperatureMotor = 0.0D;
	public double Data_TemperaturePEM = 0.0D;
	public double Data_TripMeter = 0.0D;
	public boolean Data_TrunkOpen = false;
	public String Data_VIN = "";
	public boolean Data_ValetON = false;
	public transient boolean DontAskLayoutDownload = false;
	public HashMap<String, CarData_Group> Group;
	public String NetPass = "";
	public boolean ParanoidMode = false;
	public String RegPass = "";
	public String ServerNameOrIP = "tmc.openvehicles.com";
	public String VehicleID = "";
	public String VehicleImageDrawable;
	public int lastResetVersion = 0;
}